[workspace]
resolver = "2"
members = ["kernel", "boot"]

# Default to building the boot runner
[workspace.package]
edition = "2021"
authors = ["MORNINGSTAR <morningstar@aetherion.dev>"]
license = "MIT"

# Profiles apply to all workspace members
[profile.dev]
panic = "abort"
opt-level = 1

[profile.release]
panic = "abort"
lto = false
opt-level = 2
codegen-units = 4
